### PR TITLE
support nested TAP

### PR DESCRIPTION
**Pull request by MoLow**
this fixes some tests that include nested TAP and cannot be parsed,
see https://ci.nodejs.org/job/node-test-commit-linux-containered/33495/nodes=ubuntu1804_sharedlibs_withoutssl_x64/console for example

### CODE REVIEW

**Comment by MoLow** [comment]
CC @cclauss

**Comment by MoLow** [comment]
@cclauss should a new version be published to https://pypi.org/project/tap2junit/#history ?

**Comment by cclauss** [comment]
Let’s land #39 first.

**Comment by MoLow** [comment]
> Let’s land #39 first.

Ping @cclauss

**Comment by cclauss** [comment]
I will create a release on my weekend when I can do unpaid work.

**Comment by MoLow** [comment]
thanks!

**Pull request merged**
